### ISSUE TITLE
Migrate to Spark 2.0 

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/spark-xml#137]
This should also be upgraded. I will resemble the PRs for others as soon as other data sources e.g. spark-avro and spark-redshift are done.

**Comment by HyukjinKwon** [comment]
Hi @liancheng and @cloud-fan, I am trying to release 0.3.4 (for several minor fixes)/0.4.0 (for Spark 2.0). I would appreciate if you give me some advice please.

I would like to,

 - release 0.3.4 for minot fixes first (https://github.com/databricks/spark-xml/pull/146)
 - then, upgrade to Spark 2.0 with `parseMode` introduced in https://github.com/databricks/spark-xml/pull/107
 - deprecate [`DataFrame.saveAsXmlFile`](https://github.com/databricks/spark-xml/blob/master/src/main/scala/com/databricks/spark/xml/package.scala#L85) maybe with `@deprecated("Use DataFrameWriter.write()", "0.4.0")`.
 - Release 0.4.0
 - Make a fix to avoid per-record type dispatch
 - Add `FileFormat` support, remove deprecated API's
 - Fix more issues
 - Release 0.5.0

Does that sounds okay?

**Comment by humanzz** [comment]
+1 for bringing the xml support for Spark 2.0. I hope this gets reviewed/committed/published soon!

**Comment by HyukjinKwon** [comment]
Hi @JoshRosen , I am sorry for cc you here and there. Could you just check if it is sensible what I would like to do if you don't have time to review the PRs so that I will proceed and double-checking the PRs by myself?

**Comment by HyukjinKwon** [comment]
I released 0.4.0 for Spark 2.x and 0.3.4 for Spark 1.x. Closing this.

**Comment by yatendragoel** [comment]
I am using `spark-xml_2.10-0.2.0.jar` but still facing the same issue
