### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.spark.sql.types.DecimalType$.Unlimited

### ISSUE THREAD

**Issue by witwall** [databricks/spark-xml#147]
spark-xml with spark 2.0 got the error, 
```
Error in invokeJava(isStatic = TRUE, className, methodName, ...) : 
  java.lang.NoSuchMethodError: org.apache.spark.sql.types.DecimalType$.Unlimited()Lorg/apache/spark/sql/types/DecimalType;
	at com.databricks.spark.xml.util.InferSchema$.<init>(InferSchema.scala:50)
	at com.databricks.spark.xml.util.InferSchema$.<clinit>(InferSchema.scala)
	at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:46)
	at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:46)
	at scala.Option.getOrElse(Option.scala:121)
	at com.databricks.spark.xml.XmlRelation.<init>(XmlRelation.scala:45)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:66)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:44)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:315)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
	at org.apache.spark.sql.
```

**Comment by HyukjinKwon** [comment]
Thanks for reporting this. I should upgrade this. FYI, here is the related issue https://github.com/databricks/spark-xml/issues/137

I will submit a PR soon.

**Comment by HyukjinKwon** [comment]
Let me tag this as a duplicate so that I can manage the similar issue together. If you strongly feel this is not a duplicate, I will remove the tag! Thanks again!

**Comment by jayed** [comment]
I have the same problem.

**Comment by HyukjinKwon** [comment]
I opened a PR hrre, https://github.com/databricks/spark-xml/pull/150 . I will merge some other PRs and release 0.4.0 as soon as this one is reviewed.

**Comment by nandakishore8031** [comment]
I faced the same issue too.

**Comment by HyukjinKwon** [comment]
I released 0.4.0 for Spark 2.x and 0.3.4 for Spark 1.x. So, this is resolved (manually tested). I am closing this. Please feel free to reopen if any of you faces this issue again. Thank all!

**Comment by ivaradagit** [comment]
Hello, i am using "spark-xml_2.11-0.4.1.jar" in python and i am still having the same issue. Can you please help!

**Comment by gbassan-br** [comment]
@ivaradagit use the 0.4.0 to avoid the error

**Comment by yatendragoel** [comment]
I am using `spark-xml_2.10-0.2.0.jar` but still facing the same issue

**Comment by valasatava** [comment]
I had this problem with 0.2.0. Switching to 0.4.0 solved it.

**Comment by jonjuscorpion666** [comment]
problem got resolved for me as well when switching to 0.4.0

**Comment by elghali** [comment]
same here with 0.4.0
