### ISSUE TITLE
Rows with special characters getting dropped

### ISSUE THREAD

**Issue by somasundaramsekar** [databricks/spark-xml#169]
I expect the below row to be parsed with default UTF-8, though it has some special characters, but end up getting dropped. any configurations that I'm missing or am I staring at an enhancement?

`<artist><id>4800147</id><name>Ðœ. Ð¨ÑƒÑÑ‚ÐµÑ€</name><profile></profile><data_quality>Needs Major Changes</data_quality></artist>`

```
WARN StaxXmlParser$: Dropping malformed row: <artist><id>4800147</id><name>╨£. ╨¿╤â╤?╤é╨╡╤Ç</name><profile></profile><data_quality>Needs Major Changes</data_quality></ar
tist>
```

**Comment by HyukjinKwon** [comment]
Hm. I will take a look. I think it should work okay.

**Comment by somasundaramsekar** [comment]
Here is the abt file I'm working with, also running on Windows 10

name := "dataframes"

version := "1.0"

scalaVersion := "2.11.8"

val sparkVersion="1.4.0"

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % sparkVersion % "provided",
  "org.apache.spark" %% "spark-sql" % sparkVersion,
  "com.databricks" %% "spark-xml" % "0.3.3"
)

resolvers ++= Seq(
  "Apache HBase" at "https://repository.apache.org/content/repositories/releases",
  "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
)

resolvers += Resolver.mavenLocal

**Comment by HyukjinKwon** [comment]
@somasundaramsekar Do you mind if I ask to try this with 0.3.4? It seems this was fixed somewhere.

**Comment by somasundaramsekar** [comment]
@HyukjinKwon just tried, still the same, rows are being dropped

**Comment by bjacques** [comment]
I am facing the same issue with CDATA in my XML that contains the Hex character denoted by the sequence `c0 4d 57 `. I am using spark 1.6.1, scala 2.10, spark-xml 0.4.1

Are there any unit tests around StaxXmlParser that shows this kind of UTF-8 data is handled correctly?

**Comment by srowen** [comment]
Are you sure it's not the newline in your closing tag? or is that just how it was pasted here?
It's read according to the charset you specify; are you sure it's UTF-8?
