### ISSUE TITLE
Error from reading xml from blob 

### ISSUE THREAD

**Issue by sakuraitabi2601** [databricks/spark-xml#392]
I use the following to read xml 
val df = spark.read
  .option("rowTag", "testing")
  .xml(xmlpath)

xmlpath is a wasbs://mycontainer@<accountname>.blob.core.windows.net/

but it has the following error 

shaded.databricks.org.apache.hadoop.fs.azure.AzureException: shaded.databricks.org.apache.hadoop.fs.azure.AzureException: Container mycontainer in account <accountname>.blob.core.windows.net not found, and we can't create it using anoynomous credentials, and no credentials found for them in the configuration.

what's happening

**Comment by srowen** [comment]
I don't think that's related to this library. It sounds like you don't have access to the path you're trying to read. Try reading anything else from it to confirm.

**Comment by sakuraitabi2601** [comment]
I can read another csv from the container using 
df = spark.read
  .option("sep", ",")
   .option("header","true")
  .format(csv).load(filename)

it's in the same blob container

**Comment by srowen** [comment]
Are you sure it's the same path, same container? same permissions on the data you're reading? This library doesn't do anything but delegate to the same text reader that CSV uses. I don't think there's any difference in access

**Comment by sakuraitabi2601** [comment]
yes. it's in the same container

**Comment by sakuraitabi2601** [comment]
A.
val df = spark.read
  .option("rowTag", "transactionSale")
 .xml(xmlpath)

B.
var df=spark.read.textFile(xmlpath)

A has error, B have no error 

Error for A 
shaded.databricks.org.apache.hadoop.fs.azure.AzureException: shaded.databricks.org.apache.hadoop.fs.azure.AzureException: Container mycontainer in account .blob.core.windows.net not found, and we can't create it using anoynomous credentials, and no credentials found for them in the configuration.

**Comment by sakuraitabi2601** [comment]
anyone has the idea ?

**Comment by sakuraitabi2601** [comment]
I finally found the key of the issue, I have to set the public access level of the blob storage to 
"Public read access for container and blobs" so the xml can read 

BUt is it a requirement ?? seems reading csv and other type of files doesn't require that.

**Comment by srowen** [comment]
No. This library doesn't do anything different at that level. It sounds like you have some other permissions issue on the file you read. Try reading it as textFile directly. The exact same path.

**Comment by sakuraitabi2601** [comment]
I can do it after mounting the blob container folder as a dbfs mount point 
I am not sure if there are bugs when reading directly from blob.....

**Comment by srowen** [comment]
I don't know the details of your container, but if you can read it at all, I think you have some permissions issue with the path you're reading XML from. In any event, this isn't any particular issue with this library.

**Comment by teermimi** [comment]
Exact same error here. Can read the same file with Scala and Python using 
spark.read.format("text") but fails with spark.read.format("xml") with same error message as above.

**Comment by antonmry** [comment]
It happens the same to me.  @srowen ,  should this bug be re-opened?

> val df = spark.read
>   .format("text")
>   .option("rowTag", "app")
>   .load("wasbs://xxxx-sc@xxxx.blob.core.windows.net/*.xml")

> df: org.apache.spark.sql.DataFrame = [value: string]

> val df = spark.read
>   .format("com.databricks.spark.xml")
>   .option("rowTag", "app")
>   .load("wasbs://xxxx-sc@xxxx.blob.core.windows.net/*.xml")

> shaded.databricks.org.apache.hadoop.fs.azure.AzureException: 

> shaded.databricks.org.apache.hadoop.fs.azure.AzureException: Container xxxx-sc in account xxxx.blob.core.windows.net not found, and we can't create it using anoynomous credentials, and no credentials found for them in the configuration.

**Comment by antonmry** [comment]
It isn't a bug. Solved with:

```// Using an account access key
spark.sparkContext.hadoopConfiguration.set(
  "fs.azure.account.key.<your-storage-account-name>.blob.core.windows.net",
  "<your-storage-account-access-key>"
)
``` as indicated [here](https://docs.databricks.com/spark/latest/data-sources/azure/azure-storage.html#access-azure-blob-storage-using-the-rdd-api)

**Comment by DirectWest** [comment]
> It isn't a bug. Solved with:
> 
> ```
> spark.sparkContext.hadoopConfiguration.set(
>   "fs.azure.account.key.<your-storage-account-name>.blob.core.windows.net",
>   "<your-storage-account-access-key>"
> )
> ```
> 
> as indicated [here](https://docs.databricks.com/spark/latest/data-sources/azure/azure-storage.html#access-azure-blob-storage-using-the-rdd-api)

I got an error since sparkContext does not have hadoopConfiguration, but the link helps, resolved at least my own issue by "set the Hadoop credential configuration properties as Spark configuration":

fs.azure.account.key.<storage-account-name>.blob.core.windows.net <storage-account-access-key>

**Comment by pankajdarure** [comment]
Can't believe this issue is still alive...lol
Got the exact same error while reading XML file using this package. But reading a normal text file from the same container loads perfectly fine (so obviously no issues in the access to the container) !!!
This was the error:-
`"spark-xml package org.apache.hadoop.fs.azure.AzureException,org.apache.hadoop.fs.azure.AzureException: No credentials found for account..."

`The solution is, just like setting the **_spark.conf_**, you need to set the **_spark.sparkContext._jsc.hadoopConfiguration()_** as well, see below:-
spark_config = 'fs.azure.account.key.' + blob_account_name + '.blob.core.windows.net'
spark.conf.set(spark_config, blob_access_key)
spark.sparkContext._jsc.hadoopConfiguration().set(spark_config, blob_access_key)

where, as you might have guessed, you need to replace the **_blob_account_name_** and **_blob_access_key_** above !

**Comment by TawabG** [comment]
I have faced the same issue in Azure Databricks. I have tried to manually download the spark-xml library from Maven and install it on the Databricks cluster. This enabled the spark.read.format("com.databricks.xml") feature, however it was only possible to read from dbfs instead from the storage account.
What solved the issue for me was simply updating the cluster to 14.3 LTS and changing the cluster policy to shared compute.
See: https://docs.databricks.com/en/release-notes/runtime/14.3lts.html#native-xml-file-format-support-public-preview (native XML support added).
Hope this helps other developers!
