### ISSUE TITLE
Empty field causes scala.MatchError?

### ISSUE THREAD

**Issue by larsbkrogvig** [databricks/spark-xml#80]
Hi,

I am having some issues reading a certain .xml file containing GPS data. 

The file I am trying to read contains a row that I suppose is malformed. I supply my own schema and use `failFast = false`. Instead of dropping the row, it fails. Is this intended? Or am I using the library incorrectly?

I use this schema:
```
root
 |-- @lat: double (nullable = true)
 |-- @lon: double (nullable = true)
 |-- ele: double (nullable = true)
 |-- extensions: struct (nullable = true)
 |    |-- gpxtpx:TrackPointExtension: struct (nullable = true)
 |    |    |-- gpxtpx:atemp: long (nullable = true)
 |    |    |-- gpxtpx:cad: long (nullable = true)
 |    |    |-- gpxtpx:hr: long (nullable = true)
 |-- time: string (nullable = true)
 |-- athlete: string (nullable = true)
 |-- activity_type: string (nullable = true)
```
I try to parse this file:
```
<trkseg>
 <trkpt lat="59.9155180" lon="10.6962430">
  <ele>0.0</ele>
  <time>2013-01-24T06:18:43Z</time>
  <extensions>
   <gpxtpx:TrackPointExtension>
   </gpxtpx:TrackPointExtension>
  </extensions>
 </trkpt>
</trkseg>
```
I get this error:
```
scala.MatchError: 
      (of class java.lang.String)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$com$databricks$spark$xml$parsers$StaxXmlParser$$convertObject$1.apply$mcVI$sp(StaxXmlParser.scala:218)
```
I think the problem may be caused by `<gpxtpx:TrackPointExtension>` being empty. Usually, it looks like this:
```
<gpxtpx:TrackPointExtension>
 <gpxtpx:hr>119</gpxtpx:hr>
 ...
</gpxtpx:TrackPointExtension>
```
In this case I'd perfer to have `gpxtpx:TrackPointExtension` be `null`. Alternatively, the row could be dropped. Is this a bug, or am I not seeing how I should do that?

Thanks in advance for taking the time.
Kind regards,
Lars

**Comment by Bertrandbenj** [comment]
Hi,

I have a similar issue when I let spark-xml infer my schema. it infer a like 
<a>
 <b>something here</b>
</a>

but later in the document I have the same "a" tag containing more stuff 
<a>
 <test>some other node</test>
 <b>the b node expected</b>
 some row text 
</a>

It turns out the inferred schema doesn't have the test tag. I will look at how does the schema is infered 
But I think the real issue here is that if it finds this node which structure is defined it either try to build its Structure or nullify it. And in this particular case the node contains a string (empty but what else could this node contains ... and this is a different structure).

That's just a guess so far, I'm looking at it but I think its an issue to make it a general purpose xml lib. 

having text + elements is not a good practice but it does happen and is "XML compliant"

Try to close the tag without opening it, it might work this way :
<gpxtpx:TrackPointExtension/>

**Comment by HyukjinKwon** [comment]
Thanks for reporting this and looking into this deep with a detailed description. I will try to reproduce this first.

**Comment by HyukjinKwon** [comment]
@Bertrandbenj Would you please create another issue for this? I could reproduce both cases and it looks they are separate things.

**Comment by HyukjinKwon** [comment]
@larsbkrogvig Would you please try this with 0.3.2? I just released a new one. I could reproduce this and I fixed that.

**Comment by larsbkrogvig** [comment]
@HyukjinKwon Thanks for taking a look at this issue. Unfortunately it still fails with the same error:
```
scala.MatchError: 
      (of class java.lang.String)
	at com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$com$databricks$spark$xml$parsers$StaxXmlParser$$convertObject$1.apply$mcVI$sp(StaxXmlParser.scala:210)
```
Would you like me to provide you with more information about my setup?

**Comment by HyukjinKwon** [comment]
@larsbkrogvig I wrote the file 

```xml
<?xml version="1.0"?>
<trkseg>
    <trkpt lat="59.9155180" lon="10.6962430">
        <ele>0.0</ele>
        <time>2013-01-24T06:18:43Z</time>
        <extensions>
            <gpxtpx:TrackPointExtension>
            </gpxtpx:TrackPointExtension>
        </extensions>
    </trkpt>
    <trkpt lat="52.34534522" lon="10.6342634">
        <ele>0.0</ele>
        <time>2013-01-25T06:18:43Z</time>
        <extensions>
            <gpxtpx:TrackPointExtension>
                <hr>119</hr>
            </gpxtpx:TrackPointExtension>
        </extensions>
    </trkpt>
</trkseg>

```

And then I ran this code below:

```scala
val gpsEmptyField = "your-file-path"
sqlContext.xmlFile(gpsEmptyField, treatEmptyValuesAsNulls = true, rowTag = "trkpt").show()
```

The results was below:

```
+-----------+----------+---+------------+--------------------+
|       @lat|      @lon|ele|  extensions|                time|
+-----------+----------+---+------------+--------------------+
|  59.915518| 10.696243|0.0|    [[null]]|2013-01-24T06:18:43Z|
|52.34534522|10.6342634|0.0|[[null,119]]|2013-01-25T06:18:43Z|
+-----------+----------+---+------------+--------------------+
```

**Comment by HyukjinKwon** [comment]
@larsbkrogvig Would you send me some more sample data maybe via email if you are okay?
If it fails again, I will look into this deeper with some data.

**Comment by larsbkrogvig** [comment]
@HyukjinKwon It works when I use `treatEmptyValuesAsNulls = true`, looks like I missed that earlier. Adding that to my code also solves the initial problem I had. Great! 

As far as I'm concerned this issue can now be closed. Thanks again!

**Comment by HyukjinKwon** [comment]
@larsbkrogvig Good to head.

**Comment by larsbkrogvig** [comment]
As a side note, I did try `treatEmptyValuesAsNulls = true` before 0.3.2, but it didn't work then.

**Comment by HyukjinKwon** [comment]
Yes, thanks. I think I should add some mode tags to differentiate the resolved issues among releases.
